version: "2"
services:
    qbittorrent:
        image: linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - UMASK_SET=022
            - WEBUI_PORT=8585
        volumes:
            - ./config/qbittorrent:/config
            - ./tmp/downloads:/downloads
        ports:
            - 6881:6881
            - 6881:6881/udp
            - 8585:8585
        restart: unless-stopped

    fetcher:
        image: javclub/fetcher
        container_name: fetcher
        environment: 
            - NODE_ENV=dev
        volumes: 
            - ./database:/usr/app/database
            - ./config:/usr/app/config
            - ./tmp/downloads:/downloads
            - ./tmp:/usr/app/tmp
        restart: unless-stopped
